# Generated by Django 5.0.6 on 2024-09-22 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0005_attendeeclassenrollment_last_activity_by_and_more"),
        ("facility", "0008_department_last_activity_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="facilityclass",
            name="max_enrollment",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="facilityclassenrollment",
            name="max_enrollment",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="facilityenrollment",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("expired", "Expired")],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="facultyenrollment",
            name="role",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="facilityclass",
            index=models.Index(
                fields=["slug", "name"], name="enrollment__slug_1d0018_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facilityclassenrollment",
            index=models.Index(
                fields=["facility_class", "period"],
                name="enrollment__facilit_9077a5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="facilityenrollment",
            constraint=models.UniqueConstraint(
                fields=("facility", "start", "end"), name="unique_facility_enrollment"
            ),
        ),
        migrations.AddConstraint(
            model_name="facultyenrollment",
            constraint=models.UniqueConstraint(
                fields=("faculty", "facility_enrollment", "quarters"),
                name="unique_faculty_enrollment",
            ),
        ),
    ]
