# Generated by Django 5.0.6 on 2024-10-27 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0005_rename_duration_in_weeks_course_duration_in_days_and_more"),
        ("enrollment", "0006_facilityclass_max_enrollment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilityclassenrollment",
            name="facility_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.facilityclass"
            ),
        ),
        migrations.DeleteModel(
            name="FacilityClass",
        ),
    ]
