# Generated by Django 5.0.6 on 2024-12-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0008_alter_facilityenrollment_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendeeclassenrollment",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="attendeeenrollment",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="facilityclassenrollment",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="facilityenrollment",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="factionenrollment",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="leaderenrollment",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="organizationcourse",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="organizationenrollment",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="period",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="week",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="period",
            unique_together={("slug", "week")},
        ),
        migrations.AlterUniqueTogether(
            name="week",
            unique_together={("slug", "facility_enrollment")},
        ),
    ]
