# Generated by Django 5.0.6 on 2024-12-08 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0010_alter_facultyenrollment_faculty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultyenrollment",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faculty_enrollments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Faculty",
            ),
        ),
    ]
