# Generated by Django 5.0.6 on 2024-12-08 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0011_alter_facultyenrollment_faculty"),
        ("facility", "0010_alter_facultyprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facultyenrollment",
            options={
                "ordering": ["faculty__user__last_name", "faculty__user__first_name"],
                "verbose_name": "Faculty Enrollment",
                "verbose_name_plural": "Faculty Enrollments",
            },
        ),
        migrations.AlterField(
            model_name="facultyenrollment",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faculty_enrollments",
                to="facility.facultyprofile",
                verbose_name="Faculty",
            ),
        ),
    ]
