# Generated by Django 5.0.6 on 2024-12-12 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0013_enrollment"),
        ("faction", "0012_alter_attendee_managers_remove_attendee_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendeeclassenrollment",
            options={
                "ordering": [
                    "attendee_enrollment__attendee__user__last_name",
                    "attendee_enrollment__attendee__user__first_name",
                ],
                "verbose_name": "Attendee Class Enrollment",
                "verbose_name_plural": "Attendee Class Enrollments",
            },
        ),
        migrations.AlterModelOptions(
            name="attendeeenrollment",
            options={
                "ordering": ["attendee__user__last_name", "attendee__user__first_name"],
                "verbose_name": "Attendee Enrollment",
                "verbose_name_plural": "Attendee Enrollments",
            },
        ),
        migrations.AlterField(
            model_name="attendeeenrollment",
            name="attendee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendee_enrollments",
                to="faction.attendeeprofile",
                verbose_name="Attendee",
            ),
        ),
        migrations.AlterField(
            model_name="leaderenrollment",
            name="leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leader_enrollments",
                to="faction.leaderprofile",
                verbose_name="Leader",
            ),
        ),
    ]
