# Generated by Django 5.0.6 on 2024-12-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0007_alter_facilityclass_facility_enrollment"),
        ("enrollment", "0014_alter_attendeeclassenrollment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilityenrollment",
            name="facility_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="facility_enrollments",
                to="course.facilityclass",
            ),
        ),
    ]
