# Generated by Django 5.0.6 on 2024-12-29 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0015_facilityenrollment_facility_classes"),
        ("facility", "0012_facultyprofile_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facultyclassenrollment",
            options={
                "ordering": ["faculty__user__last_name", "faculty__user__first_name"],
                "verbose_name": "Faculty Class Enrollment",
                "verbose_name_plural": "Faculty Class Enrollments",
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="facultyclassenrollment",
                    name="faculty",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_enrollments",
                        to="facility.facultyprofile",
                        verbose_name="Faculty",
                    ),
                )
            ],
        ),
    ]
