# Generated by Django 5.0.6 on 2025-01-24 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0017_facultyenrollment_created_at_and_more"),
        ("facility", "0012_facultyprofile_slug"),
        ("faction", "0014_attendeeprofile_slug_leaderprofile_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendeeclassenrollment",
            options={
                "ordering": ["attendee__user__last_name", "attendee__user__first_name"],
                "verbose_name": "Attendee Class Enrollment",
                "verbose_name_plural": "Attendee Class Enrollments",
            },
        ),
        migrations.AlterModelOptions(
            name="leaderenrollment",
            options={
                "ordering": ["leader__user__last_name", "leader__user__first_name"],
                "verbose_name": "Leader Enrollment",
                "verbose_name_plural": "Leader Enrollments",
            },
        ),
        migrations.RemoveField(
            model_name="attendeeclassenrollment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="attendeeclassenrollment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="attendeeclassenrollment",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="attendeeclassenrollment",
            name="description",
        ),
        migrations.RemoveField(
            model_name="attendeeclassenrollment",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="attendeeclassenrollment",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="attendeeclassenrollment",
            name="last_activity_by",
        ),
        migrations.RemoveField(
            model_name="attendeeclassenrollment",
            name="name",
        ),
        migrations.RemoveField(
            model_name="attendeeclassenrollment",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="attendeeclassenrollment",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="attendeeclassenrollment",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="leaderenrollment",
            name="end",
        ),
        migrations.RemoveField(
            model_name="leaderenrollment",
            name="start",
        ),
        migrations.AddField(
            model_name="attendeeclassenrollment",
            name="attendee",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_enrollments",
                to="faction.attendeeprofile",
                verbose_name="Faculty",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendeeenrollment",
            name="role",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="leaderenrollment",
            name="role",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="attendeeclassenrollment",
            name="attendee_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_enrollments",
                to="enrollment.attendeeenrollment",
                verbose_name="Attendee Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="attendeeclassenrollment",
            name="facility_class_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendee_class_enrollments",
                to="enrollment.facilityclassenrollment",
                verbose_name="Facility Class Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="facultyenrollment",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="leaderenrollment",
            name="quarters",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leader_enrollments",
                to="facility.quarters",
                verbose_name="Quarters",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="attendeeenrollment",
            constraint=models.UniqueConstraint(
                fields=("attendee", "faction_enrollment", "quarters"),
                name="unique_attendee_enrollment",
            ),
        ),
        migrations.AddConstraint(
            model_name="leaderenrollment",
            constraint=models.UniqueConstraint(
                fields=("leader", "faction_enrollment", "quarters"),
                name="unique_leader_enrollment",
            ),
        ),
    ]
