# Generated by Django 5.0.6 on 2025-01-25 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0018_alter_attendeeclassenrollment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="factionenrollment",
            name="facility_enrollment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faction_enrollments",
                to="enrollment.facilityenrollment",
                verbose_name="Facility Enrollment",
            ),
            preserve_default=False,
        ),
    ]
