# Generated by Django 5.2.8 on 2025-11-21 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0019_factionenrollment_facility_enrollment"),
        (
            "facility",
            "0015_alter_facultyprofile_options_alter_facility_address_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilityClassAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity", models.PositiveIntegerField()),
                ("reserved", models.PositiveIntegerField(default=0)),
                ("on_hold", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility_class_enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="enrollment.facilityclassenrollment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["facility_class_enrollment"],
                        name="enrollment__facilit_058ca4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="QuartersWeekAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity", models.PositiveIntegerField()),
                ("reserved", models.PositiveIntegerField(default=0)),
                ("on_hold", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility_enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarters_availability",
                        to="enrollment.facilityenrollment",
                    ),
                ),
                (
                    "quarters",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week_availability",
                        to="facility.quarters",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarters_availability",
                        to="enrollment.week",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["facility_enrollment", "week"],
                        name="enrollment__facilit_377a3f_idx",
                    )
                ],
                "unique_together": {("week", "quarters")},
            },
        ),
    ]
