# Generated by Django 5.2.8 on 2025-11-21 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0020_facilityclassavailability_quartersweekavailability"),
        (
            "facility",
            "0015_alter_facultyprofile_options_alter_facility_address_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyQuartersAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capacity", models.PositiveIntegerField()),
                ("reserved", models.PositiveIntegerField(default=0)),
                ("on_hold", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility_enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_quarters_availability",
                        to="enrollment.facilityenrollment",
                    ),
                ),
                (
                    "quarters",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_availability",
                        to="facility.quarters",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["facility_enrollment", "quarters"],
                        name="enrollment__facilit_2b42cd_idx",
                    )
                ],
                "unique_together": {("facility_enrollment", "quarters")},
            },
        ),
    ]
