# Generated by Django 5.2.8 on 2025-11-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0021_facultyquartersavailability"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendeeenrollment",
            name="end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendeeenrollment",
            name="start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facultyenrollment",
            name="end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facultyenrollment",
            name="start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaderenrollment",
            name="end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaderenrollment",
            name="start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
