# Generated by Django 5.2.8 on 2025-11-23 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0022_attendeeenrollment_end_attendeeenrollment_start_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activeenrollment",
            name="attendee_enrollment",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_attendee_enrollments",
                to="enrollment.attendeeenrollment",
                verbose_name="Attendee Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="activeenrollment",
            name="facility_enrollment",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_facility_enrollments",
                to="enrollment.facilityenrollment",
                verbose_name="Facility Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="activeenrollment",
            name="faction_enrollment",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_faction_enrollments",
                to="enrollment.factionenrollment",
                verbose_name="Faction Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="activeenrollment",
            name="faculty_enrollment",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_faculty_enrollments",
                to="enrollment.facultyenrollment",
                verbose_name="Faculty Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="activeenrollment",
            name="leader_enrollment",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_leader_enrollments",
                to="enrollment.leaderenrollment",
                verbose_name="Leader Enrollment",
            ),
        ),
    ]
