# Generated by Codex on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0023_alter_activeenrollment_attendee_enrollment_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="facilityclassenrollment",
            constraint=models.UniqueConstraint(
                fields=("facility_class", "period", "department"),
                name="unique_facility_class_period_department",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendeeclassenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("facility_class_enrollment__isnull", False)),
                fields=("attendee", "facility_class_enrollment"),
                name="unique_attendee_class_assignment",
                violation_error_message=(
                    "This enrollment conflicts with an existing assignment."
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="facultyclassenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("facility_class_enrollment__isnull", False)),
                fields=("faculty", "facility_class_enrollment"),
                name="unique_faculty_class_assignment",
                violation_error_message=(
                    "This enrollment conflicts with an existing assignment."
                ),
            ),
        ),
    ]
